# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/ACCESS-NRI/ACCESS-MED
  rev: v0.1.1
  hooks:
  - id: jb-to-sphinx
    args: ["./docs"]
